---
- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['git', 'make', 'python3-psycopg2', 'virtualenv', 'tar', 'bzip2']
    - name: Deploy cert
      copy:
        src: files/certificates/bioinf-galactus.erasmusmc.nl.crt
        dest: /etc/ssl/certs/bioinf-galactus.erasmusmc.nl.crt
        owner: root
        group: root
        mode: '0644'
    - name: Deploy key
      copy:
        src: files/certificates/bioinf-galactus.erasmusmc.nl.key
        dest: /etc/ssl/private/bioinf-galactus.erasmusmc.nl.key
        owner: root
        group: root
        mode: '0400'
  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted
  roles:
    - htcondor-github
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - usegalaxy_eu.galaxy_systemd
    - galaxyproject.gxadmin
    - galaxyproject.nginx
    - galaxyproject.proftpd
    - galaxyproject.cvmfs
    - influxdata.chrony
