galaxy_commit_id: release_24.1

# Certbot
certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_auth_method: --webroot
certbot_install_method: virtualenv
certbot_auto_renew: yes
certbot_auto_renew_user: root
certbot_environment: production
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - www-data
certbot_post_renewal: |
    systemctl restart nginx || true
certbot_domains:
 - "{{ inventory_hostname }}"
certbot_agree_tos: --agree-tos

# Galaxy Customisations
galaxy_root: /srv/galaxy
galaxy_data_directory: /data/xnat-data/galaxy-data
galaxy_brand: "🔬"
galaxy_mutable_data_dir: "{{ galaxy_data_directory }}/var"
galaxy_enable_registration: no

nginx_servers:
  - redirect-ssl
nginx_ssl_servers:
  - galaxy
nginx_ssl_role: usegalaxy_eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-www-data.pem


# Overriding
galaxy_config_templates:
  - src: templates/galaxy/config/job_conf.surf.xml.j2
    dest: "{{ galaxy_config.galaxy.job_config_file }}"
  - src: templates/galaxy/config/user_preferences_extra_conf.yml
    dest: "{{ galaxy_config.galaxy.user_preferences_extra_conf_path }}"
  - src: templates/galaxy/config/oidc_backends_config.surf.xml
    dest: "{{ galaxy_config.galaxy.oidc_backends_config_file }}"
  - src: templates/galaxy/config/oidc_config.surf.xml
    dest: "{{ galaxy_config.galaxy.oidc_config_file }}"
  - src: "templates/galaxy/config/file_sources.yml"
    dest: "{{ galaxy_config.galaxy.file_sources_config_file }}"
  - src: "templates/galaxy/config/trs_servers_conf.yml"
    dest: "{{ galaxy_config.galaxy.trs_servers_config_file }}"
  - src: "templates/galaxy/config/custom_tools.xml"
    dest: "{{ galaxy_config_dir }}/emc-tool-conf.xml"
  - src: "templates/galaxy/config/error_report.yml"
    dest: "{{ galaxy_config.galaxy.error_report_file }}"
